2025-04-14 20:25:18,155 INFO    MainThread:2403862 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-14 20:25:18,155 INFO    MainThread:2403862 [wandb_setup.py:_flush():67] Configure stats pid to 2403862
2025-04-14 20:25:18,155 INFO    MainThread:2403862 [wandb_setup.py:_flush():67] Loading settings from /home/yuvraj/.config/wandb/settings
2025-04-14 20:25:18,155 INFO    MainThread:2403862 [wandb_setup.py:_flush():67] Loading settings from /home/yuvraj/YuvrajML/vjproject/vj_project/wandb/settings
2025-04-14 20:25:18,155 INFO    MainThread:2403862 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-14 20:25:18,155 INFO    MainThread:2403862 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/yuvraj/YuvrajML/vjproject/vj_project/wandb/offline-run-20250414_202518-hmqsswdf/logs/debug.log
2025-04-14 20:25:18,156 INFO    MainThread:2403862 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/yuvraj/YuvrajML/vjproject/vj_project/wandb/offline-run-20250414_202518-hmqsswdf/logs/debug-internal.log
2025-04-14 20:25:18,156 INFO    MainThread:2403862 [wandb_init.py:init():781] calling init triggers
2025-04-14 20:25:18,156 INFO    MainThread:2403862 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-14 20:25:18,156 INFO    MainThread:2403862 [wandb_init.py:init():809] starting backend
2025-04-14 20:25:18,582 INFO    MainThread:2403862 [wandb_init.py:init():813] sending inform_init request
2025-04-14 20:25:18,609 INFO    MainThread:2403862 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-14 20:25:18,610 INFO    MainThread:2403862 [wandb_init.py:init():823] backend started and connected
2025-04-14 20:25:18,613 INFO    MainThread:2403862 [wandb_init.py:init():915] updated telemetry
2025-04-14 20:25:18,615 INFO    MainThread:2403862 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-14 20:25:18,735 INFO    MainThread:2403862 [wandb_init.py:init():1014] starting run threads in backend
2025-04-14 20:25:18,853 INFO    MainThread:2403862 [wandb_run.py:_console_start():2454] atexit reg
2025-04-14 20:25:18,853 INFO    MainThread:2403862 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-14 20:25:18,853 INFO    MainThread:2403862 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-14 20:25:18,853 INFO    MainThread:2403862 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-14 20:25:18,855 INFO    MainThread:2403862 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-14 20:25:31,596 WARNING MsgRouterThr:2403862 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/yuvraj/miniconda3/envs/vjenv/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-14 20:25:31,598 INFO    MsgRouterThr:2403862 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 0 handles.
